
// types para el authReducer.js y el authActions.js
export const INICIAR_SESION = 'INICIAR_SESION';
export const INICIAR_SESION_CORRECTO = 'INICIAR_SESION_CORRECTO';
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';


// types para alertReducer.js
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// types para usersReducer.js y usersActions.js
export const OBTENER_USUARIOS_CORRECTO = 'OBTENER_USUARIOS_CORRECTO';
export const OBTENER_USUARIOS_ERROR = 'OBTENER_USUARIOS_ERROR';

export const AGREGAR_USUARIO_CORRECTO = 'AGREGAR_USUARIO_CORRECTO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const ACTUALIZAR_USUARIO_CORRECTO = 'ACTUALIZAR_USUARIO_CORRECTO';
export const ACTUALIZAR_USUARIO_ERROR = 'ACTUALIZAR_USUARIO_ERROR';

export const ELIMINAR_USUARIO_CORRECTO = 'ELIMINAR_USUARIO_CORRECTO';
export const ELIMINAR_USUARIO_ERROR = 'ELIMINAR_USUARIO_ERROR';

export const ABRIR_MODAL = 'ABRIR_MODAL';
export const CERRAR_MODAL = 'CERRAR_MODAL';

export const USUARIO_SELECCIONADO = 'USUARIO_SELECCIONADO';

export const LIMPIAR_USUARIO = 'LIMPIAR_USUARIO';
export const LIMPIAR_USUARIOS = 'LIMPIAR_USUARIOS';