
// types para el authReducer.js y el authActions.js
export const INICIAR_SESION = 'INICIAR_SESION';
export const INICIAR_SESION_CORRECTO = 'INICIAR_SESION_CORRECTO';
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';


// types para alertReducer.js
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// types para usersReducer.js y usersActions.js
export const OBTENER_USUARIOS_CORRECTO = 'OBTENER_USUARIOS_CORRECTO';
export const OBTENER_USUARIOS_ERROR = 'OBTENER_USUARIOS_ERROR';

export const AGREGAR_USUARIO_CORRECTO = 'AGREGAR_USUARIO_CORRECTO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const ACTUALIZAR_USUARIO_CORRECTO = 'ACTUALIZAR_USUARIO_CORRECTO';
export const ACTUALIZAR_USUARIO_ERROR = 'ACTUALIZAR_USUARIO_ERROR';

export const ELIMINAR_USUARIO_CORRECTO = 'ELIMINAR_USUARIO_CORRECTO';
export const ELIMINAR_USUARIO_ERROR = 'ELIMINAR_USUARIO_ERROR';

export const ABRIR_MODAL_USUARIO = 'ABRIR_MODAL_USUARIO';
export const CERRAR_MODAL_USUARIO = 'CERRAR_MODAL_USUARIO';

export const USUARIO_SELECCIONADO = 'USUARIO_SELECCIONADO';

export const LIMPIAR_ESTADO_USUARIOS = 'LIMPIAR_ESTADO_USUARIOS';


// types para clientsAction.js y clientsReducer.js
export const OBTENER_CLIENTES_CORRECTO = 'OBTENER_CLIENTES_CORRECTO';
export const OBTENER_CLIENTES_ERROR = 'OBTENER_CLIENTES_ERROR';

export const AGREGAR_CLIENTE_CORRECTO = 'AGREGAR_CLIENTE_CORRECTO';
export const AGREGAR_CLIENTE_ERROR = 'AGREGAR_CLIENTE_ERROR';

export const ACTUALIZAR_CLIENTE_CORRECTO = 'ACTUALIZAR_CLIENTE_CORRECTO';
export const ACTUALIZAR_CLIENTE_ERROR = 'ACTUALIZAR_CLIENTE_ERROR';

export const ELIMINAR_CLIENTE_CORRECTO = 'ELIMINAR_CLIENTE_CORRECTO';
export const ELIMINAR_CLIENTE_ERROR = 'ELIMINAR_CLIENTE_ERROR';

export const ABRIR_MODAL_CLIENTE = 'ABRIR_MODAL_CLIENTE';
export const CERRAR_MODAL_CLIENTE = 'CERRAR_MODAL_CLIENTE';

export const CLIENTE_SELECCIONADO = 'CLIENTE_SELECCIONADO';

export const LIMPIAR_ESTADO_CLIENTES = 'LIMPIAR_ESTADO_CLIENTES';

// types para devicesAction.js y devicesReducer.js
export const OBTENER_DISPOSITIVOS_CORRECTO = 'OBTENER_DISPOSITIVOS_CORRECTO';
export const OBTENER_DISPOSITIVOS_ERROR = 'OBTENER_DISPOSITIVOS_ERROR';

export const AGREGAR_DISPOSITIVO_CORRECTO = 'AGREGAR_DISPOSITIVO_CORRECTO';
export const AGREGAR_DISPOSITIVO_ERROR = 'AGREGAR_DISPOSITIVO_ERROR';

export const ACTUALIZAR_DISPOSITIVO_CORRECTO = 'ACTUALIZAR_DISPOSITIVO_CORRECTO';
export const ACTUALIZAR_DISPOSITIVO_ERROR = 'ACTUALIZAR_DISPOSITIVO_ERROR';

export const ELIMINAR_DISPOSITIVO_CORRECTO = 'ELIMINAR_DISPOSITIVO_CORRECTO';
export const ELIMINAR_DISPOSITIVO_ERROR = 'ELIMINAR_DISPOSITIVO_ERROR';

export const ABRIR_MODAL_DISPOSITIVO = 'ABRIR_MODAL_DISPOSITIVO';
export const CERRAR_MODAL_DISPOSITIVO = 'CERRAR_MODAL_DISPOSITIVO';

export const DISPOSITIVO_SELECCIONADO = 'DISPOSITIVO_SELECCIONADO';

export const LIMPIAR_ESTADO_DISPOSITIVOS = 'LIMPIAR_ESTADO_DISPOSITIVOS';